version: '3.7'

services:
    db:
        image: mongo
        restart: always
        container_name: testepagarme-db
        environment:
            - MONGO_DATA-DIR=/data/db
        ports:
            - 27020:27017
        expose:
            - '27017'
        volumes:
            - /data/est-crm-db:/data/db:z
        command: mongod --smallfiles
